import random
from dataclasses import dataclass, replace


@dataclass(frozen=True, slots=True)
class SeedExample:
    id: int
    category: str
    level: str
    user_text: str
    target_behavior: str
    tone: str
    should_correct: bool | str
    variation_count: int = 6
    notes: str = ""

    @property
    def category_key(self) -> str:
        return self.category

    @property
    def text(self) -> str:
        return self.user_text


BASE_SEED_EXAMPLES: list[SeedExample] = [
    SeedExample(
        id=1,
        category="awkward_english",
        level="B",
        user_text="I am boring today.",
        target_behavior="brief_correction_then_continue",
        tone="casual",
        should_correct=True,
        notes="Briefly correct the expression to 'I'm bored today,' then continue the conversation naturally.",
    ),
    SeedExample(
        id=2,
        category="awkward_english",
        level="B",
        user_text="Yesterday I go to cafe.",
        target_behavior="brief_correction_then_continue",
        tone="encouraging",
        should_correct=True,
        notes="Briefly correct it to a natural past-tense sentence, then continue with a simple follow-up.",
    ),
    SeedExample(
        id=3,
        category="small_talk",
        level="B",
        user_text="I had coffee three times today.",
        target_behavior="natural_conversation",
        tone="playful",
        should_correct=False,
        notes="Respond playfully and keep the conversation casual.",
    ),
    SeedExample(
        id=4,
        category="small_talk",
        level="B",
        user_text="The weather feels weird today.",
        target_behavior="ask_simple_followup",
        tone="casual",
        should_correct=False,
        notes="Respond naturally and ask a light follow-up about the weather or the user's mood.",
    ),
    SeedExample(
        id=5,
        category="topic_request",
        level="B",
        user_text="Can you give me a topic?",
        target_behavior="offer_topic",
        tone="casual",
        should_correct=False,
        notes="Offer one natural conversation topic and one follow-up question suitable for a B-level learner.",
    ),
    SeedExample(
        id=6,
        category="spoken_short_reply",
        level="B",
        user_text="Maybe.",
        target_behavior="ask_simple_followup",
        tone="casual",
        should_correct=False,
        notes="Treat it as uncertainty and gently help the user continue.",
    ),
    SeedExample(
        id=7,
        category="spoken_short_reply",
        level="B",
        user_text="Not really.",
        target_behavior="repair_conversation",
        tone="casual",
        should_correct=False,
        notes="Do not let the conversation die after a short reply. Offer a small pivot or follow-up.",
    ),
    SeedExample(
        id=8,
        category="emotion_checkin",
        level="B",
        user_text="I feel kind of empty today.",
        target_behavior="respond_with_empathy",
        tone="warm",
        should_correct=False,
        notes="Respond warmly without sounding overly therapeutic.",
    ),
    SeedExample(
        id=9,
        category="emotion_checkin",
        level="B",
        user_text="I am tired but I cannot sleep well.",
        target_behavior="respond_with_empathy",
        tone="supportive",
        should_correct=False,
        notes="Prioritize empathy and natural conversation over correction.",
    ),
    SeedExample(
        id=10,
        category="conversation_recovery",
        level="B",
        user_text="I don't know what to talk about.",
        target_behavior="repair_conversation",
        tone="casual",
        should_correct=False,
        notes="Offer one easy but not childish topic instead of ending the turn.",
    ),
    SeedExample(
        id=11,
        category="conversation_recovery",
        level="B",
        user_text="Wait, that's not what I meant.",
        target_behavior="repair_conversation",
        tone="warm",
        should_correct=False,
        notes="Acknowledge the correction and invite the user to clarify naturally.",
    ),
    SeedExample(
        id=12,
        category="correction_request",
        level="B",
        user_text="Is 'I am hard to wake up' natural?",
        target_behavior="explain_naturally",
        tone="neutral",
        should_correct=True,
        notes="Give a short correction and one or two natural alternatives.",
    ),
    SeedExample(
        id=13,
        category="correction_request",
        level="B",
        user_text="Can you correct my English?",
        target_behavior="brief_correction_then_continue",
        tone="casual",
        should_correct=True,
        notes="Invite the user to send a sentence and explain that corrections will be short and natural.",
    ),
    SeedExample(
        id=14,
        category="confidence_issue",
        level="B",
        user_text="I feel nervous when I speak English.",
        target_behavior="encourage_confidence",
        tone="encouraging",
        should_correct=False,
        notes="Encourage the user and keep the language natural for a B-level learner.",
    ),
    SeedExample(
        id=15,
        category="confidence_issue",
        level="B",
        user_text="I think my English is too bad to talk a lot.",
        target_behavior="encourage_confidence",
        tone="supportive",
        should_correct=False,
        notes="Reassure the user without over-praising or giving a long lecture.",
    ),
    SeedExample(
        id=16,
        category="mixed_language",
        level="B",
        user_text="오늘 너무 tired 해서 아무것도 하기 싫어.",
        target_behavior="respond_with_empathy",
        tone="warm",
        should_correct=False,
        notes="Respond mostly in natural English, with brief Korean support only if it helps clarity.",
    ),
    SeedExample(
        id=17,
        category="mixed_language",
        level="B",
        user_text="I want to speak more naturally, but 자꾸 말이 끊겨.",
        target_behavior="encourage_confidence",
        tone="supportive",
        should_correct=False,
        notes="Acknowledge the difficulty and suggest a simple way to keep speaking.",
    ),
    SeedExample(
        id=18,
        category="natural_expression",
        level="B",
        user_text="Can you tell me a more natural way to say this?",
        target_behavior="explain_naturally",
        tone="casual",
        should_correct=True,
        notes="Ask for the sentence if missing, then provide a natural expression with a short explanation.",
    ),
    SeedExample(
        id=19,
        category="opinion_chat",
        level="B",
        user_text="Do you think staying home is better than going out?",
        target_behavior="natural_conversation",
        tone="casual",
        should_correct=False,
        notes="Share a balanced opinion and invite the user's preference.",
    ),
    SeedExample(
        id=20,
        category="preference_chat",
        level="B",
        user_text="I think movies are better at home than in theaters.",
        target_behavior="ask_simple_followup",
        tone="casual",
        should_correct=False,
        notes="Respond to the opinion naturally and ask a follow-up about movie habits.",
    ),
    SeedExample(
        id=21,
        category="humor_banter",
        level="B",
        user_text="I think my alarm clock hates me.",
        target_behavior="natural_conversation",
        tone="playful",
        should_correct=False,
        notes="Keep the joke going lightly without overdoing the banter.",
    ),
    SeedExample(
        id=22,
        category="hesitation_repair",
        level="B",
        user_text="Um... I don't know how to explain this well.",
        target_behavior="repair_conversation",
        tone="warm",
        should_correct=False,
        notes="Help the user express the idea step by step.",
    ),
    SeedExample(
        id=23,
        category="learning_preference",
        level="B",
        user_text="I want to study English by talking, not by grammar first.",
        target_behavior="explain_naturally",
        tone="encouraging",
        should_correct=False,
        notes="Accept the preference and explain that conversation-first practice is fine.",
    ),
    SeedExample(
        id=24,
        category="social_english",
        level="B",
        user_text="Can you help me answer more naturally?",
        target_behavior="explain_naturally",
        tone="casual",
        should_correct=False,
        notes="Help the user say something more naturally in conversation without turning it into a texting task.",
    ),
    SeedExample(
        id=25,
        category="pronunciation_talk",
        level="B",
        user_text="Why is this word hard for me to pronounce?",
        target_behavior="explain_naturally",
        tone="casual",
        should_correct=False,
        variation_count=4,
        notes="Explain in simple terms and avoid technical phonetics unless clearly useful.",
    ),
    SeedExample(
        id=26,
        category="safety_boundary",
        level="B",
        user_text="How do I say something rude without sounding rude?",
        target_behavior="soften_expression",
        tone="neutral",
        should_correct=False,
        variation_count=4,
        notes="Set a calm boundary and redirect to a respectful, assertive alternative.",
    ),
    SeedExample(
        id=27,
        category="awkward_english",
        level="B",
        user_text="I want speak English better.",
        target_behavior="brief_correction_then_continue",
        tone="encouraging",
        should_correct=True,
        notes="Briefly correct it to 'I want to speak English better,' then continue naturally.",
    ),
    SeedExample(
        id=28,
        category="awkward_english",
        level="B",
        user_text="I don't know what should I say.",
        target_behavior="brief_correction_then_continue",
        tone="casual",
        should_correct=True,
        notes="Briefly suggest 'I don't know what I should say' or 'I don't know what to say,' then keep the conversation going.",
    ),
    SeedExample(
        id=29,
        category="awkward_english",
        level="B",
        user_text="My condition is not good today.",
        target_behavior="brief_correction_then_continue",
        tone="warm",
        should_correct="optional",
        notes="If useful, suggest 'I don't feel great today' and respond with empathy.",
    ),
    SeedExample(
        id=30,
        category="awkward_english",
        level="B",
        user_text="I have many stress these days.",
        target_behavior="brief_correction_then_continue",
        tone="supportive",
        should_correct=True,
        notes="Briefly correct it to 'I've been under a lot of stress lately,' then respond with empathy.",
    ),
    SeedExample(
        id=31,
        category="spoken_short_reply",
        level="B",
        user_text="I don't know.",
        target_behavior="repair_conversation",
        tone="casual",
        should_correct=False,
        notes="Treat it as a short spoken reply and keep the conversation moving naturally.",
    ),
    SeedExample(
        id=32,
        category="spoken_short_reply",
        level="B",
        user_text="I guess.",
        target_behavior="ask_simple_followup",
        tone="casual",
        should_correct=False,
        notes="Treat the answer as mild uncertainty and ask a natural follow-up.",
    ),
    SeedExample(
        id=33,
        category="spoken_short_reply",
        level="B",
        user_text="Haha.",
        target_behavior="natural_conversation",
        tone="playful",
        should_correct=False,
        notes="Treat it as a light spoken reaction and keep the banter going.",
    ),
    SeedExample(
        id=34,
        category="topic_request",
        level="B",
        user_text="Let's talk about something easy.",
        target_behavior="offer_topic",
        tone="casual",
        should_correct=False,
        notes="Offer one easy but engaging topic suitable for a B-level learner.",
    ),
    SeedExample(
        id=35,
        category="topic_request",
        level="B",
        user_text="Can you ask me a question?",
        target_behavior="offer_topic",
        tone="casual",
        should_correct=False,
        notes="Ask one open but easy question that invites a real answer.",
    ),
    SeedExample(
        id=36,
        category="conversation_recovery",
        level="B",
        user_text="Sorry, I lost my train of thought.",
        target_behavior="repair_conversation",
        tone="warm",
        should_correct=False,
        notes="Help the user reset without pressure.",
    ),
    SeedExample(
        id=37,
        category="conversation_recovery",
        level="B",
        user_text="Never mind.",
        target_behavior="repair_conversation",
        tone="casual",
        should_correct=False,
        notes="Respect the user's withdrawal and offer a gentle topic change.",
    ),
    SeedExample(
        id=38,
        category="daily_routine",
        level="B",
        user_text="I woke up late today.",
        target_behavior="natural_conversation",
        tone="casual",
        should_correct=False,
        notes="Respond naturally and ask about the rest of the day.",
    ),
    SeedExample(
        id=39,
        category="daily_routine",
        level="B",
        user_text="I usually just stay home after work.",
        target_behavior="ask_simple_followup",
        tone="casual",
        should_correct=False,
        notes="Ask a natural follow-up about how the user spends time at home.",
    ),
    SeedExample(
        id=40,
        category="daily_routine",
        level="B",
        user_text="My day was pretty normal.",
        target_behavior="natural_conversation",
        tone="casual",
        should_correct=False,
        notes="Avoid making the conversation boring; find a small angle to continue.",
    ),
    SeedExample(
        id=41,
        category="preference_chat",
        level="B",
        user_text="I prefer texting to calling.",
        target_behavior="natural_conversation",
        tone="casual",
        should_correct=False,
        notes="Respond to the preference naturally and compare texting vs calling.",
    ),
    SeedExample(
        id=42,
        category="preference_chat",
        level="B",
        user_text="I don't really like parties.",
        target_behavior="ask_simple_followup",
        tone="warm",
        should_correct=False,
        notes="Respond without judging and ask about the user's preferred social setting.",
    ),
    SeedExample(
        id=43,
        category="social_english",
        level="B",
        user_text="How can I start a conversation with someone new?",
        target_behavior="explain_naturally",
        tone="casual",
        should_correct=False,
        notes="Give practical, natural conversation openers and keep the explanation short.",
    ),
    SeedExample(
        id=44,
        category="social_english",
        level="B",
        user_text="What should I say when the conversation gets awkward?",
        target_behavior="explain_naturally",
        tone="encouraging",
        should_correct=False,
        notes="Give simple phrases that help recover awkward moments naturally.",
    ),
    SeedExample(
        id=45,
        category="natural_expression",
        level="B",
        user_text="How can I say '귀찮아' naturally?",
        target_behavior="explain_naturally",
        tone="casual",
        should_correct=True,
        notes="Provide natural options like 'I don't feel like it' or 'I can't be bothered,' and explain the tone briefly.",
    ),
    SeedExample(
        id=46,
        category="repair_my_sentence",
        level="B",
        user_text="Can you make this sentence sound more natural?",
        target_behavior="explain_naturally",
        tone="casual",
        should_correct=True,
        notes="Ask the user to send the sentence if it is missing, then rewrite it naturally.",
    ),
    SeedExample(
        id=47,
        category="clarification_request",
        level="B",
        user_text="Can you say that more simply?",
        target_behavior="explain_naturally",
        tone="casual",
        should_correct=False,
        notes="Simplify the sentence clearly without sounding condescending.",
    ),
    SeedExample(
        id=48,
        category="casual_slang",
        level="B",
        user_text="What does 'I'm down' mean?",
        target_behavior="explain_naturally",
        tone="casual",
        should_correct=False,
        notes="Explain the phrase, mention when it is used, and give one natural example.",
    ),
    SeedExample(
        id=49,
        category="roleplay_conversation",
        level="B",
        user_text="Can we practice ordering coffee?",
        target_behavior="roleplay_start",
        tone="casual",
        should_correct=False,
        notes="Start the roleplay immediately and keep it natural for a B-level learner.",
    ),
    SeedExample(
        id=50,
        category="long_context",
        level="B",
        user_text="I want to become more confident when I speak English.",
        target_behavior="encourage_confidence",
        tone="supportive",
        should_correct=False,
        variation_count=8,
        notes="Use this seed to generate longer conversations about confidence, practice habits, and speaking fluency.",
    ),
    SeedExample(
        id=51,
        category="small_talk",
        level="B",
        user_text="I didn't do much today, honestly.",
        target_behavior="natural_conversation",
        tone="casual",
        should_correct=False,
        notes="Keep the conversation going even if the user's day sounds uneventful.",
    ),
    SeedExample(
        id=52,
        category="small_talk",
        level="B",
        user_text="I was just lying around at home.",
        target_behavior="ask_simple_followup",
        tone="casual",
        should_correct=False,
        notes="Respond casually and find a light follow-up that feels natural on a call.",
    ),
    SeedExample(
        id=53,
        category="clarification_request",
        level="B",
        user_text="Wait, what do you mean by that?",
        target_behavior="explain_naturally",
        tone="casual",
        should_correct=False,
        notes="Rephrase clearly and simply without sounding stiff or academic.",
    ),
    SeedExample(
        id=54,
        category="clarification_request",
        level="B",
        user_text="Sorry, I didn't catch that part.",
        target_behavior="explain_naturally",
        tone="warm",
        should_correct=False,
        notes="Repeat or paraphrase naturally as if speaking on a call.",
    ),
    SeedExample(
        id=55,
        category="long_context",
        level="B",
        user_text="I keep starting English study plans, but I stop after a few days.",
        target_behavior="encourage_confidence",
        tone="supportive",
        should_correct=False,
        variation_count=8,
        notes="Generate longer conversations that stay on the topic of habits, setbacks, and realistic next steps.",
    ),
    SeedExample(
        id=56,
        category="long_context",
        level="B",
        user_text="I want to talk more smoothly, but my mind goes blank in the middle.",
        target_behavior="repair_conversation",
        tone="supportive",
        should_correct=False,
        variation_count=8,
        notes="Generate longer conversations about hesitation, recovery, and keeping a spoken conversation going.",
    ),
]


A_LEVEL_USER_TEXTS: dict[int, str] = {
    1: "I boring today.",
    2: "Yesterday I go cafe.",
    3: "I drank coffee three times today.",
    4: "Weather is strange today.",
    5: "Give me topic, please.",
    6: "Maybe...",
    7: "Not much.",
    8: "I feel empty today.",
    9: "I am tired and can't sleep well.",
    10: "I don't know what to say.",
    11: "Wait, not that.",
    12: "Is 'I am hard to wake up' okay?",
    13: "Can you fix my English?",
    14: "I feel nervous speaking English.",
    15: "My English is bad, so I can't talk much.",
    16: "오늘 너무 tired. 아무것도 하기 싫어.",
    17: "I want speak naturally, but 자꾸 stop.",
    18: "Tell me natural way to say this.",
    19: "Is staying home better than going out?",
    20: "Movies at home are better.",
    21: "My alarm clock hate me.",
    22: "Um... I can't explain good.",
    23: "I want study English by talking, not grammar.",
    24: "Can you help me answer naturally?",
    25: "Why this word is hard to say?",
    26: "How can I say rude thing not too rude?",
    27: "I want speak English more better.",
    28: "I don't know what I say.",
    29: "My body condition bad today.",
    30: "These days I have many stress.",
    31: "I don't know.",
    32: "Maybe, I think.",
    33: "Haha.",
    34: "Let's talk easy thing.",
    35: "Ask me one question.",
    36: "Sorry, I forgot what I say.",
    37: "It's okay. Never mind.",
    38: "I woke up late.",
    39: "After work, I just stay home.",
    40: "My day was normal.",
    41: "I like texting more than calling.",
    42: "I don't like parties much.",
    43: "How do I start talk with new person?",
    44: "What can I say when talk gets awkward?",
    45: "How do I say '귀찮아' in English?",
    46: "Can you make this sentence natural?",
    47: "Can you say it easy?",
    48: "What is 'I'm down' mean?",
    49: "Can we practice order coffee?",
    50: "I want more confidence when I speak English.",
    51: "I didn't do much today.",
    52: "I was just at home all day.",
    53: "Wait, what do you mean?",
    54: "Sorry, I didn't hear that part.",
    55: "I start English study plans, but I stop fast.",
    56: "I want talk smoothly, but my mind goes blank.",
}


C_LEVEL_USER_TEXTS: dict[int, str] = {
    1: "I've been feeling a bit dull and unmotivated today.",
    2: "I went to a cafe yesterday, but saying it naturally still trips me up.",
    3: "I've already had coffee three times today, so I'm basically running on caffeine now.",
    4: "The weather feels oddly off today, and I can't quite explain why.",
    5: "Could you give me an interesting conversation topic to talk about?",
    6: "Maybe, but I'm not completely sure yet.",
    7: "Not really, if I'm being honest.",
    8: "I feel kind of emotionally drained and empty today.",
    9: "I'm exhausted, but my sleep has been so restless lately.",
    10: "I'm not sure what to talk about right now, and my mind feels blank.",
    11: "Wait, that's not quite what I meant to say.",
    12: "Does 'I am hard to wake up' sound natural, or is there a better way to say it?",
    13: "Could you correct my English and make it sound more natural?",
    14: "I get pretty nervous whenever I have to speak English out loud.",
    15: "I feel like my English isn't good enough to keep a conversation going for long.",
    16: "오늘은 너무 exhausted해서 진짜 아무것도 하고 싶지 않아.",
    17: "I want to sound more natural in English, but 자꾸 말이 끊겨서 답답해.",
    18: "Could you show me a more natural and idiomatic way to say this?",
    19: "Do you think staying in is better than going out, or does it just depend on the mood?",
    20: "I honestly think watching movies at home is better than going to a theater most of the time.",
    21: "I'm convinced my alarm clock has a personal grudge against me.",
    22: "Um... I'm having trouble putting this into words clearly.",
    23: "I'd rather improve my English through conversation first instead of starting with grammar drills.",
    24: "Could you help me answer in a more natural way?",
    25: "Why does this word feel so awkward for me to pronounce?",
    26: "How can I say something blunt without sounding unnecessarily rude?",
    27: "I want to speak English more fluently and naturally.",
    28: "I never know what I'm supposed to say in moments like this.",
    29: "I'm not feeling my best today, physically or mentally.",
    30: "I've been under a lot of stress lately, and it's starting to wear me down.",
    31: "I honestly don't know.",
    32: "I guess so, but I'm not fully confident about it.",
    33: "Haha, that's actually pretty funny.",
    34: "Let's talk about something easy but still interesting.",
    35: "Could you ask me a question to get the conversation started?",
    36: "Sorry, I completely lost my train of thought for a second.",
    37: "Actually, never mind. It doesn't really matter.",
    38: "I overslept and ended up waking up later than I meant to today.",
    39: "After work, I usually just stay home and keep things low-key.",
    40: "My day was pretty ordinary overall, and nothing especially interesting happened.",
    41: "I definitely prefer texting over calling most of the time.",
    42: "I'm not really a fan of parties, to be honest.",
    43: "How do you usually start a conversation with someone you've just met?",
    44: "What should I say when a conversation starts getting awkward or quiet?",
    45: "What's a natural English way to say '귀찮아' depending on the situation?",
    46: "Could you make this sentence sound smoother and more natural?",
    47: "Could you explain that again in a simpler way?",
    48: "What does 'I'm down' usually mean in casual conversation?",
    49: "Could we roleplay ordering coffee so I can practice sounding natural?",
    50: "I want to become genuinely more confident and comfortable when I speak English.",
    51: "I honestly didn't do much today, so I don't even know what to talk about.",
    52: "I mostly just stayed home and lazed around all day.",
    53: "Wait, what exactly do you mean by that?",
    54: "Sorry, I didn't quite catch that part. Could you say it a little differently?",
    55: "I keep making English study plans, but I lose momentum after a few days.",
    56: "I want to speak more smoothly, but my mind goes blank halfway through a conversation.",
}


def build_level_variants(
    base_seeds: list[SeedExample],
    level: str,
    id_offset: int,
    user_texts: dict[int, str],
) -> list[SeedExample]:
    return [
        replace(
            seed,
            id=seed.id + id_offset,
            level=level,
            user_text=user_texts[seed.id],
        )
        for seed in base_seeds
    ]


SEED_EXAMPLES: list[SeedExample] = [
    *BASE_SEED_EXAMPLES,
    *build_level_variants(BASE_SEED_EXAMPLES, level="A", id_offset=100, user_texts=A_LEVEL_USER_TEXTS),
    *build_level_variants(BASE_SEED_EXAMPLES, level="C", id_offset=200, user_texts=C_LEVEL_USER_TEXTS),
]


def list_seed_examples() -> list[dict[str, object]]:
    return [
        {
            "id": seed.id,
            "category": seed.category,
            "level": seed.level,
            "user_text": seed.user_text,
            "target_behavior": seed.target_behavior,
            "tone": seed.tone,
            "should_correct": seed.should_correct,
            "variation_count": seed.variation_count,
            "notes": seed.notes,
        }
        for seed in SEED_EXAMPLES
    ]


def get_seed_by_id(seed_id: int) -> SeedExample:
    for seed in SEED_EXAMPLES:
        if seed.id == seed_id:
            return seed
    raise ValueError(f"Unknown seed number: {seed_id}")


def get_random_seed(rng: random.Random | None = None) -> SeedExample:
    chooser = rng or random
    return chooser.choice(SEED_EXAMPLES)
